import { NextResponse } from "next/server";
import { z } from "zod";
import { publicWebsiteSchema } from "@/lib/security/url";
import { MockAuditProvider } from "@/lib/providers/mock";
import { SafeWebsiteCrawler } from "@/lib/providers/crawler";
import { buildTechnicalAuditIssues, crawlEvidenceToTechnicalObservation } from "@/lib/engines/technical-audit";
import { getAuditRunRepository } from "@/lib/repositories/audit-runs";
import type { EvidenceReference } from "@/lib/domain/types";
export const runtime="nodejs";
const schema=z.object({url:publicWebsiteSchema});
export async function POST(request:Request){const body:unknown=await request.json().catch(()=>null);const parsed=schema.safeParse(body);if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message??"Invalid URL"},{status:400});const provider=new MockAuditProvider();const repository=getAuditRunRepository();const startedAt=new Date().toISOString();if(process.env.OPENGROWTH_REAL_CRAWL==="true"){try{const crawler=new SafeWebsiteCrawler();const crawl=await crawler.crawl(parsed.data.url,{timeoutMs:Number(process.env.CRAWLER_TIMEOUT_MS??5000),maxBytes:Number(process.env.CRAWLER_MAX_BYTES??300000)});const observedAt=new Date().toISOString();const evidence:Partial<EvidenceReference>[]=[{id:"ev-live-crawl-page",kind:"CRAWL_OBSERVATION",source:"SafeWebsiteCrawler",observedAt,retrievedAt:observedAt,reliability:"MEDIUM",isEstimated:false,isSimulated:false,summary:`Fetched ${crawl.finalUrl} and normalized ${crawl.wordCount} words, ${crawl.headings.length} headings, ${crawl.imageCount} images and ${crawl.internalLinkCount} internal links.`,normalizedValue:crawl}];const observation=crawlEvidenceToTechnicalObservation(crawl);const issues=buildTechnicalAuditIssues({pages:[observation],evidenceIds:{metadata:"ev-live-crawl-page",schema:"ev-live-crawl-page",links:"ev-live-crawl-page",alt:"ev-live-crawl-page",performance:"ev-live-crawl-page"}});const run=await repository.save({projectId:"northstar",url:parsed.data.url,source:"safe-crawler",status:"completed",startedAt,completedAt:observedAt,simulatedIssues:false,issues,evidence,crawl});return NextResponse.json({runId:run.id,issues,source:"safe-crawler",url:parsed.data.url,crawl,evidence,simulatedIssues:false})}catch(error){const completedAt=new Date().toISOString();const issues=await provider.audit(parsed.data.url);const crawlError=error instanceof Error?error.message:"Crawler failed";const run=await repository.save({projectId:"northstar",url:parsed.data.url,source:"simulated-fallback",status:"fallback",startedAt,completedAt,simulatedIssues:true,issues,evidence:[],crawlError});return NextResponse.json({runId:run.id,issues,source:"simulated-fallback",url:parsed.data.url,crawlError,simulatedIssues:true},{status:200})}}const completedAt=new Date().toISOString();const issues=await provider.audit(parsed.data.url);const run=await repository.save({projectId:"northstar",url:parsed.data.url,source:"simulated",status:"completed",startedAt,completedAt,simulatedIssues:true,issues,evidence:[]});return NextResponse.json({runId:run.id,issues,source:"simulated",url:parsed.data.url,simulatedIssues:true})}
