"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useLiveAnalyze } from "@/lib/client/live-project";
import { BarChart3, BookOpen, Bot, Building2, ChevronDown, FileSearch, LayoutDashboard, Menu, Radar, Settings, Swords, Target, TrendingUp, Wrench, X } from "lucide-react";
import { useState } from "react";
import { Brand } from "./brand";
const navGroups=[["Analyze",[["/demo/dashboard","Next actions",LayoutDashboard],["/demo/business","Business graph",Building2],["/demo/audit","Audit workspace",FileSearch],["/demo/site-intelligence","Site intelligence",Wrench]]],["Grow",[["/demo/opportunities","Opportunities",Target],["/demo/content","Content planner",BookOpen],["/demo/ai-visibility","AI visibility",Radar],["/demo/competitors","Competitors",Swords]]],["Measure",[["/demo/outcomes","Outcomes",TrendingUp]]],["Workspace",[["/demo/assistant","Growth assistant",Bot],["/demo/settings","Project settings",Settings]]]] as const;
export function WorkspaceShell({children}:{children:React.ReactNode}){const path=usePathname();const [open,setOpen]=useState(false);const {result}=useLiveAnalyze();const brand=result?.project.brandGuess;const domain=result?.project.domain;return <div className="workspace"><aside className={`workspace-side ${open?"open":""}`}><div className="side-head"><Brand href="/demo/dashboard"/><button className="icon-btn mobile-only" onClick={()=>setOpen(false)} aria-label="Close navigation"><X size={19}/></button></div><button className="project-switch"><span className="project-avatar">{brand?brand.charAt(0).toUpperCase():"\u2013"}</span><span><b>{brand??"No project"}</b><small>{domain??"Run a scan to begin"}</small></span><ChevronDown size={15}/></button><nav className="side-nav">{navGroups.map(([group,items])=><div className="side-group" key={group}><span className="side-group-label">{group}</span>{items.map(([href,label,Icon])=><Link key={href} href={href} className={path.startsWith(href)?"active":""} onClick={()=>setOpen(false)}><Icon size={18}/>{label}</Link>)}</div>)}</nav><div className="side-bottom"><Link href="/demo/community"><BarChart3 size={18}/> Community playbooks <span className="soon">Soon</span></Link><Link href="/" className="fine">← Back to marketing site</Link></div></aside><div className="workspace-body"><header className="workspace-top"><button className="icon-btn mobile-only" onClick={()=>setOpen(true)} aria-label="Open navigation"><Menu size={21}/></button><div><b>{brand??"No project"}</b>{domain?<span className="fine"> · {domain}</span>:null}</div><div className="top-right"><button className="avatar" aria-label="Account">—</button></div></header><main className="workspace-main">{children}</main></div>{open&&<button className="nav-scrim" onClick={()=>setOpen(false)} aria-label="Close menu"/>}</div>}
